In [1]:
import numpy as np

1. Array (Dizi)

In [2]:
dizi = np.array([0, 1, 2, 3])
dizi

array([0, 1, 2, 3])

In [3]:
yas_dizi = np.array([18, 25, 22, 34, 26, 27, 19, 28, 30, 24])
boy_dizi = np.array([1.81, 1.67, 1.71, 1.89, 1.79, 1.75, 1.80, 1.78, 1.89, 1.82])
agirlik_dizi = np.array([81, 72, 74, 88, 82, 77, 78, 70, 90, 85])

In [4]:
print(yas_dizi.shape)
print(boy_dizi.shape)
print(agirlik_dizi.shape)
# shape ile dizinin boyutunu öğrenebiliriz.

(10,)
(10,)
(10,)


In [5]:
Listem = ['Ali', 13, True]
Dizi = np.array(Listem)

print(Dizi)
# Farklı tipte elemanlardan oluşan bir dizi oluşturmak istediğimizde, elemanlar ortak bir tipe dönüşür.

['Ali' '13' 'True']


In [6]:
dizi = np.array([0, 1, 2, 3])
dizi[2:] = [5,4]
print(dizi)

[0 1 5 4]


DİZİLERDE DEĞİŞİKLİK YAPMA

In [7]:
dizi = np.array([0, 1, 2, 3])
dizi[2:] = [8]
print(dizi)

[0 1 8 8]


In [8]:
dizi = np.array([0, 1, 2, 3])
np.append(dizi, (7,8,9))
# append ile dizilere ekleme yapabiliriz.

array([0, 1, 2, 3, 7, 8, 9])

ÇOK BOYUTLU DİZİLER

In [9]:
w = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
basketbol_takimi = np.array([[18, 25, 22, 34, 26, 27, 19, 28, 30, 24],
                        [1.81, 1.67, 1.71, 1.89, 1.79, 1.75, 1.80, 1.78, 1.89, 1.82],
                        [81, 72, 74, 88, 82, 77, 78, 70, 90, 85]])
print(basketbol_takimi)

print(basketbol_takimi.shape)

[[18.   25.   22.   34.   26.   27.   19.   28.   30.   24.  ]
 [ 1.81  1.67  1.71  1.89  1.79  1.75  1.8   1.78  1.89  1.82]
 [81.   72.   74.   88.   82.   77.   78.   70.   90.   85.  ]]
(3, 10)


In [11]:
y = np.arange(8).reshape(2, 4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Dizinin elemalarına ulaşma

In [12]:
basketbol_takimi[0, 3]

34.0

In [13]:
basketbol_takimi[0,]

array([18., 25., 22., 34., 26., 27., 19., 28., 30., 24.])

In [14]:
basketbol_takimi[0:4:2]

array([[18., 25., 22., 34., 26., 27., 19., 28., 30., 24.],
       [81., 72., 74., 88., 82., 77., 78., 70., 90., 85.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [18]:
np.linspace(0,20,9)
# linspace ile sabit aralıklarla dizioluşturulur.

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [19]:
np.eye(5)
# Identity Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

NUMPY FONKSİYONLARI

In [20]:
x = np.array([0, 1, 2, 3])

print(np.square(x))

[0 1 4 9]


In [21]:
x = np.array([0, 1, 2, 3])

print(np.sqrt(x))

[0.         1.         1.41421356 1.73205081]


In [22]:
print(np.cos(x))
print(np.sin(x))
print(np.tan(x))

[ 1.          0.54030231 -0.41614684 -0.9899925 ]
[0.         0.84147098 0.90929743 0.14112001]
[ 0.          1.55740772 -2.18503986 -0.14254654]


In [23]:
print(np.max(yas_dizi))
print(np.max(agirlik_dizi))
print(np.max(boy_dizi))

34
90
1.89


In [24]:
print(np.min(yas_dizi))
print(np.min(agirlik_dizi))
print(np.min(boy_dizi))

18
70
1.67


In [25]:
print(np.mean(yas_dizi))
print(np.mean(agirlik_dizi))
print(np.mean(boy_dizi))

25.3
79.7
1.791


In [26]:
print(np.std(yas_dizi))
print(np.std(agirlik_dizi))
print(np.std(boy_dizi))

4.627094120503711
6.372597586541928
0.06624952830020753
